import { randomBytes } from 'node:crypto';

/**
 * Monotonic ULID generator (https://github.com/ulid/spec).
 *
 * 48-bit millisecond timestamp + 80 bits of randomness, Crockford base32.
 * IDs sort lexicographically by creation time, which makes them usable as
 * pagination cursors ("messages after X"). Within the same millisecond the
 * random part is incremented so IDs generated by this process stay strictly
 * increasing. Because better-sqlite3 is synchronous and this server is a
 * single process, rows are committed in ID order.
 */
const ALPHABET = '0123456789ABCDEFGHJKMNPQRSTVWXYZ';

let lastTime = -1;
let lastRandom: Uint8Array = new Uint8Array(10);

function encodeTime(time: number): string {
  let out = '';
  let t = time;
  for (let i = 0; i < 10; i++) {
    out = ALPHABET[t % 32] + out;
    t = Math.floor(t / 32);
  }
  return out;
}

function encodeRandom(bytes: Uint8Array): string {
  // 80 bits → 16 base32 characters.
  let out = '';
  let buffer = 0;
  let bits = 0;
  for (const byte of bytes) {
    buffer = (buffer << 8) | byte;
    bits += 8;
    while (bits >= 5) {
      out += ALPHABET[(buffer >>> (bits - 5)) & 31];
      bits -= 5;
    }
    buffer &= (1 << bits) - 1;
  }
  return out;
}

function increment(bytes: Uint8Array): Uint8Array {
  const next = new Uint8Array(bytes);
  for (let i = next.length - 1; i >= 0; i--) {
    if (next[i] === 255) {
      next[i] = 0;
    } else {
      next[i] = (next[i] ?? 0) + 1;
      return next;
    }
  }
  throw new Error('ULID random component overflow');
}

export function newId(now: number = Date.now()): string {
  if (now <= lastTime) {
    lastRandom = increment(lastRandom);
    return encodeTime(lastTime) + encodeRandom(lastRandom);
  }
  lastTime = now;
  lastRandom = new Uint8Array(randomBytes(10));
  // Keep headroom so increments within one millisecond never overflow.
  lastRandom[0] = (lastRandom[0] ?? 0) & 0x7f;
  return encodeTime(now) + encodeRandom(lastRandom);
}

/** Smallest possible ULID for a timestamp — useful for "messages since <date>" filters. */
export function idFloorForTime(time: number): string {
  return encodeTime(Math.max(0, time)) + '0'.repeat(16);
}

export function timeFromId(id: string): number {
  let t = 0;
  for (const ch of id.slice(0, 10)) t = t * 32 + ALPHABET.indexOf(ch);
  return t;
}

/**
 * Non-monotonic ULID for an explicit (past) timestamp. Only for seeding/backfills,
 * where rows must be created in increasing time order by the caller.
 */
export function newIdAt(time: number): string {
  const random = new Uint8Array(randomBytes(10));
  return encodeTime(time) + encodeRandom(random);
}
