/**
 * Relational schema (SQLite via Drizzle ORM).
 *
 * Conventions
 *  - IDs are ULIDs (text, time-sortable) generated by the server.
 *  - Timestamps are INTEGER milliseconds since the Unix epoch.
 *  - JSON columns hold small bounded arrays/objects only.
 *  - Users are never hard-deleted: account deletion anonymises the row so
 *    foreign keys from messages stay valid (see docs/ARCHITECTURE.md → Data retention).
 *
 * After editing this file run `npm run db:generate` to create a migration.
 */
import { sql } from 'drizzle-orm';
import {
  type AnySQLiteColumn,
  check,
  foreignKey,
  index,
  integer,
  primaryKey,
  sqliteTable,
  text,
  uniqueIndex,
} from 'drizzle-orm/sqlite-core';
import type {
  Discipline,
  DmPolicy,
  NotificationPrefs,
  PlatformRole,
  PresencePreference,
  ProfileLink,
} from '@creator-network/shared';

export const users = sqliteTable(
  'users',
  {
    id: text('id').primaryKey(),
    username: text('username').notNull(),
    email: text('email').notNull(),
    emailVerifiedAt: integer('email_verified_at'),
    passwordHash: text('password_hash').notNull(),
    displayName: text('display_name').notNull(),
    avatarId: text('avatar_id').references((): AnySQLiteColumn => uploads.id, { onDelete: 'set null' }),
    headline: text('headline').notNull().default(''),
    bio: text('bio').notNull().default(''),
    disciplines: text('disciplines', { mode: 'json' }).$type<Discipline[]>().notNull().default(sql`'[]'`),
    location: text('location').notNull().default(''),
    timezone: text('timezone').notNull().default(''),
    links: text('links', { mode: 'json' }).$type<ProfileLink[]>().notNull().default(sql`'[]'`),
    currentProjects: text('current_projects').notNull().default(''),
    bannerHue: integer('banner_hue'),
    platformRole: text('platform_role').$type<PlatformRole>().notNull().default('member'),
    status: text('status').$type<'active' | 'suspended' | 'deleted'>().notNull().default('active'),
    suspendedUntil: integer('suspended_until'),
    suspensionReason: text('suspension_reason'),
    presence: text('presence').$type<PresencePreference>().notNull().default('online'),
    dmPolicy: text('dm_policy').$type<DmPolicy>().notNull().default('everyone'),
    notificationPrefs: text('notification_prefs', { mode: 'json' })
      .$type<Partial<NotificationPrefs>>()
      .notNull()
      .default(sql`'{}'`),
    mutedCommunityIds: text('muted_community_ids', { mode: 'json' }).$type<string[]>().notNull().default(sql`'[]'`),
    onboardingCompletedAt: integer('onboarding_completed_at'),
    isDemo: integer('is_demo', { mode: 'boolean' }).notNull().default(false),
    createdAt: integer('created_at').notNull(),
    updatedAt: integer('updated_at').notNull(),
    deletedAt: integer('deleted_at'),
  },
  (t) => [
    uniqueIndex('users_username_uq').on(t.username),
    uniqueIndex('users_email_uq').on(t.email),
    index('users_status_idx').on(t.status),
    check('users_platform_role_ck', sql`${t.platformRole} in ('member','moderator','admin')`),
    check('users_status_ck', sql`${t.status} in ('active','suspended','deleted')`),
  ],
);

export const sessions = sqliteTable(
  'sessions',
  {
    id: text('id').primaryKey(),
    userId: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    /** SHA-256 of the cookie token. The raw token is never stored. */
    tokenHash: text('token_hash').notNull(),
    userAgent: text('user_agent').notNull().default(''),
    ip: text('ip').notNull().default(''),
    createdAt: integer('created_at').notNull(),
    lastSeenAt: integer('last_seen_at').notNull(),
    expiresAt: integer('expires_at').notNull(),
  },
  (t) => [
    uniqueIndex('sessions_token_hash_uq').on(t.tokenHash),
    index('sessions_user_idx').on(t.userId),
    index('sessions_expires_idx').on(t.expiresAt),
  ],
);

export const emailTokens = sqliteTable(
  'email_tokens',
  {
    id: text('id').primaryKey(),
    userId: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    purpose: text('purpose').$type<'verify_email' | 'reset_password'>().notNull(),
    tokenHash: text('token_hash').notNull(),
    /** Address the token was issued for (email verification). */
    email: text('email').notNull().default(''),
    createdAt: integer('created_at').notNull(),
    expiresAt: integer('expires_at').notNull(),
    usedAt: integer('used_at'),
  },
  (t) => [
    uniqueIndex('email_tokens_hash_uq').on(t.tokenHash),
    index('email_tokens_user_idx').on(t.userId, t.purpose),
    check('email_tokens_purpose_ck', sql`${t.purpose} in ('verify_email','reset_password')`),
  ],
);

export const uploads = sqliteTable(
  'uploads',
  {
    id: text('id').primaryKey(),
    uploaderId: text('uploader_id')
      .notNull()
      .references((): AnySQLiteColumn => users.id, { onDelete: 'cascade' }),
    purpose: text('purpose').$type<'attachment' | 'avatar' | 'community_icon'>().notNull(),
    channelId: text('channel_id').references((): AnySQLiteColumn => channels.id, { onDelete: 'set null' }),
    messageId: text('message_id').references((): AnySQLiteColumn => messages.id, { onDelete: 'set null' }),
    /** Sanitised original file name, shown to users and used for downloads. */
    name: text('name').notNull(),
    mime: text('mime').notNull(),
    size: integer('size').notNull(),
    /** Path relative to the uploads directory. Never exposed to clients. */
    storageKey: text('storage_key').notNull(),
    width: integer('width'),
    height: integer('height'),
    durationMs: integer('duration_ms'),
    waveform: text('waveform', { mode: 'json' }).$type<number[]>(),
    status: text('status').$type<'pending' | 'attached' | 'deleted'>().notNull().default('pending'),
    createdAt: integer('created_at').notNull(),
  },
  (t) => [
    index('uploads_message_idx').on(t.messageId),
    index('uploads_status_idx').on(t.status, t.createdAt),
    index('uploads_uploader_idx').on(t.uploaderId),
    check('uploads_purpose_ck', sql`${t.purpose} in ('attachment','avatar','community_icon')`),
    check('uploads_status_ck', sql`${t.status} in ('pending','attached','deleted')`),
  ],
);

export const communities = sqliteTable(
  'communities',
  {
    id: text('id').primaryKey(),
    name: text('name').notNull(),
    description: text('description').notNull().default(''),
    iconId: text('icon_id').references(() => uploads.id, { onDelete: 'set null' }),
    visibility: text('visibility').$type<'public' | 'private'>().notNull().default('private'),
    tags: text('tags', { mode: 'json' }).$type<string[]>().notNull().default(sql`'[]'`),
    ownerId: text('owner_id')
      .notNull()
      .references(() => users.id),
    memberCount: integer('member_count').notNull().default(0),
    isDemo: integer('is_demo', { mode: 'boolean' }).notNull().default(false),
    createdAt: integer('created_at').notNull(),
    updatedAt: integer('updated_at').notNull(),
  },
  (t) => [
    index('communities_visibility_idx').on(t.visibility, t.memberCount),
    index('communities_owner_idx').on(t.ownerId),
    check('communities_visibility_ck', sql`${t.visibility} in ('public','private')`),
  ],
);

export const communityMembers = sqliteTable(
  'community_members',
  {
    communityId: text('community_id')
      .notNull()
      .references(() => communities.id, { onDelete: 'cascade' }),
    userId: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    joinedAt: integer('joined_at').notNull(),
  },
  (t) => [primaryKey({ columns: [t.communityId, t.userId] }), index('community_members_user_idx').on(t.userId)],
);

export const roles = sqliteTable(
  'roles',
  {
    id: text('id').primaryKey(),
    communityId: text('community_id')
      .notNull()
      .references(() => communities.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    color: text('color'),
    /** Higher position = higher in the hierarchy. @everyone is always 0. */
    position: integer('position').notNull(),
    permissions: integer('permissions').notNull().default(0),
    isDefault: integer('is_default', { mode: 'boolean' }).notNull().default(false),
    hoist: integer('hoist', { mode: 'boolean' }).notNull().default(false),
    createdAt: integer('created_at').notNull(),
  },
  (t) => [index('roles_community_idx').on(t.communityId, t.position)],
);

export const memberRoles = sqliteTable(
  'member_roles',
  {
    communityId: text('community_id').notNull(),
    userId: text('user_id').notNull(),
    roleId: text('role_id')
      .notNull()
      .references(() => roles.id, { onDelete: 'cascade' }),
  },
  (t) => [
    primaryKey({ columns: [t.communityId, t.userId, t.roleId] }),
    index('member_roles_role_idx').on(t.roleId),
    foreignKey({
      name: 'member_roles_member_fk',
      columns: [t.communityId, t.userId],
      foreignColumns: [communityMembers.communityId, communityMembers.userId],
    }).onDelete('cascade'),
  ],
);

export const channelCategories = sqliteTable(
  'channel_categories',
  {
    id: text('id').primaryKey(),
    communityId: text('community_id')
      .notNull()
      .references(() => communities.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    position: integer('position').notNull().default(0),
    createdAt: integer('created_at').notNull(),
  },
  (t) => [index('channel_categories_community_idx').on(t.communityId)],
);

export const channels = sqliteTable(
  'channels',
  {
    id: text('id').primaryKey(),
    kind: text('kind').$type<'text' | 'dm' | 'group_dm'>().notNull(),
    communityId: text('community_id').references((): AnySQLiteColumn => communities.id, { onDelete: 'cascade' }),
    categoryId: text('category_id').references(() => channelCategories.id, { onDelete: 'set null' }),
    name: text('name').notNull().default(''),
    topic: text('topic').notNull().default(''),
    position: integer('position').notNull().default(0),
    /** Group DM owner (can rename / add / remove participants). */
    ownerId: text('owner_id').references((): AnySQLiteColumn => users.id, { onDelete: 'set null' }),
    /** For 1:1 DMs: "<smallerUserId>:<largerUserId>" — guarantees one DM per pair. */
    dmKey: text('dm_key'),
    lastMessageId: text('last_message_id'),
    lastMessageAt: integer('last_message_at'),
    createdAt: integer('created_at').notNull(),
    updatedAt: integer('updated_at').notNull(),
  },
  (t) => [
    index('channels_community_idx').on(t.communityId, t.position),
    uniqueIndex('channels_dm_key_uq').on(t.dmKey),
    check('channels_kind_ck', sql`${t.kind} in ('text','dm','group_dm')`),
    check(
      'channels_scope_ck',
      sql`(${t.kind} = 'text' and ${t.communityId} is not null) or (${t.kind} <> 'text' and ${t.communityId} is null)`,
    ),
  ],
);

export const channelOverwrites = sqliteTable(
  'channel_overwrites',
  {
    channelId: text('channel_id')
      .notNull()
      .references(() => channels.id, { onDelete: 'cascade' }),
    targetType: text('target_type').$type<'role' | 'member'>().notNull(),
    targetId: text('target_id').notNull(),
    allow: integer('allow').notNull().default(0),
    deny: integer('deny').notNull().default(0),
  },
  (t) => [
    primaryKey({ columns: [t.channelId, t.targetType, t.targetId] }),
    check('channel_overwrites_type_ck', sql`${t.targetType} in ('role','member')`),
  ],
);

export const channelParticipants = sqliteTable(
  'channel_participants',
  {
    channelId: text('channel_id')
      .notNull()
      .references(() => channels.id, { onDelete: 'cascade' }),
    userId: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    joinedAt: integer('joined_at').notNull(),
  },
  (t) => [primaryKey({ columns: [t.channelId, t.userId] }), index('channel_participants_user_idx').on(t.userId)],
);

export const invites = sqliteTable(
  'invites',
  {
    code: text('code').primaryKey(),
    communityId: text('community_id')
      .notNull()
      .references(() => communities.id, { onDelete: 'cascade' }),
    inviterId: text('inviter_id').references(() => users.id, { onDelete: 'set null' }),
    /** When set, only this user can redeem the invite (direct invitation). */
    targetUserId: text('target_user_id').references(() => users.id, { onDelete: 'cascade' }),
    maxUses: integer('max_uses'),
    uses: integer('uses').notNull().default(0),
    expiresAt: integer('expires_at'),
    revokedAt: integer('revoked_at'),
    createdAt: integer('created_at').notNull(),
  },
  (t) => [index('invites_community_idx').on(t.communityId), index('invites_target_idx').on(t.targetUserId)],
);

/** Codes that allow registration while the instance is in invite-only mode. */
export const registrationInvites = sqliteTable('registration_invites', {
  code: text('code').primaryKey(),
  createdBy: text('created_by').references(() => users.id, { onDelete: 'set null' }),
  note: text('note').notNull().default(''),
  maxUses: integer('max_uses'),
  uses: integer('uses').notNull().default(0),
  expiresAt: integer('expires_at'),
  revokedAt: integer('revoked_at'),
  createdAt: integer('created_at').notNull(),
});

export const communityBans = sqliteTable(
  'community_bans',
  {
    communityId: text('community_id')
      .notNull()
      .references(() => communities.id, { onDelete: 'cascade' }),
    userId: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    reason: text('reason').notNull().default(''),
    bannedBy: text('banned_by').references(() => users.id, { onDelete: 'set null' }),
    createdAt: integer('created_at').notNull(),
  },
  (t) => [primaryKey({ columns: [t.communityId, t.userId] })],
);

export const messages = sqliteTable(
  'messages',
  {
    /**
     * Stable integer rowid alias. The full-text index (messages_fts, see the
     * custom migration) is keyed by this column; an explicit INTEGER PRIMARY KEY
     * guarantees rowids never change on VACUUM.
     */
    seq: integer('seq').primaryKey(),
    id: text('id').notNull(),
    channelId: text('channel_id')
      .notNull()
      .references(() => channels.id, { onDelete: 'cascade' }),
    authorId: text('author_id')
      .notNull()
      .references(() => users.id),
    content: text('content').notNull(),
    kind: text('kind').$type<'default' | 'system'>().notNull().default('default'),
    replyToId: text('reply_to_id').references((): AnySQLiteColumn => messages.id, { onDelete: 'set null' }),
    /** Client-generated idempotency key: a retried send never creates a duplicate. */
    nonce: text('nonce'),
    mentionEveryone: integer('mention_everyone', { mode: 'boolean' }).notNull().default(false),
    editedAt: integer('edited_at'),
    deletedAt: integer('deleted_at'),
    pinnedAt: integer('pinned_at'),
    pinnedBy: text('pinned_by'),
    createdAt: integer('created_at').notNull(),
    updatedAt: integer('updated_at').notNull(),
  },
  (t) => [
    uniqueIndex('messages_id_uq').on(t.id),
    index('messages_channel_idx').on(t.channelId, t.id),
    index('messages_author_idx').on(t.authorId, t.id),
    uniqueIndex('messages_author_nonce_uq').on(t.authorId, t.nonce),
    index('messages_pinned_idx')
      .on(t.channelId, t.pinnedAt)
      .where(sql`${t.pinnedAt} is not null`),
    check('messages_kind_ck', sql`${t.kind} in ('default','system')`),
  ],
);

export const messageMentions = sqliteTable(
  'message_mentions',
  {
    messageId: text('message_id')
      .notNull()
      .references(() => messages.id, { onDelete: 'cascade' }),
    userId: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
  },
  (t) => [primaryKey({ columns: [t.messageId, t.userId] }), index('message_mentions_user_idx').on(t.userId, t.messageId)],
);

export const messageReactions = sqliteTable(
  'message_reactions',
  {
    messageId: text('message_id')
      .notNull()
      .references(() => messages.id, { onDelete: 'cascade' }),
    userId: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    emoji: text('emoji').notNull(),
    createdAt: integer('created_at').notNull(),
  },
  (t) => [primaryKey({ columns: [t.messageId, t.emoji, t.userId] })],
);

export const readStates = sqliteTable(
  'read_states',
  {
    userId: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    channelId: text('channel_id')
      .notNull()
      .references(() => channels.id, { onDelete: 'cascade' }),
    lastReadId: text('last_read_id'),
    updatedAt: integer('updated_at').notNull(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.channelId] })],
);

export const notifications = sqliteTable(
  'notifications',
  {
    id: text('id').primaryKey(),
    userId: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    type: text('type').notNull(),
    actorId: text('actor_id').references(() => users.id, { onDelete: 'set null' }),
    communityId: text('community_id').references(() => communities.id, { onDelete: 'cascade' }),
    channelId: text('channel_id').references(() => channels.id, { onDelete: 'cascade' }),
    messageId: text('message_id').references(() => messages.id, { onDelete: 'set null' }),
    data: text('data', { mode: 'json' }).$type<Record<string, unknown>>().notNull().default(sql`'{}'`),
    count: integer('count').notNull().default(1),
    readAt: integer('read_at'),
    createdAt: integer('created_at').notNull(),
    updatedAt: integer('updated_at').notNull(),
  },
  (t) => [
    index('notifications_user_idx').on(t.userId, t.updatedAt),
    index('notifications_unread_idx').on(t.userId, t.readAt),
    index('notifications_channel_idx').on(t.channelId),
  ],
);

export const userBlocks = sqliteTable(
  'user_blocks',
  {
    blockerId: text('blocker_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    blockedId: text('blocked_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    createdAt: integer('created_at').notNull(),
  },
  (t) => [primaryKey({ columns: [t.blockerId, t.blockedId] }), index('user_blocks_blocked_idx').on(t.blockedId)],
);

export const reports = sqliteTable(
  'reports',
  {
    id: text('id').primaryKey(),
    reporterId: text('reporter_id').references(() => users.id, { onDelete: 'set null' }),
    targetType: text('target_type').$type<'message' | 'user' | 'community'>().notNull(),
    targetId: text('target_id').notNull(),
    communityId: text('community_id'),
    reason: text('reason').notNull(),
    details: text('details').notNull().default(''),
    /** Copy of the reported content at report time, so evidence survives edits/deletion. */
    snapshot: text('snapshot', { mode: 'json' }).$type<Record<string, unknown>>().notNull().default(sql`'{}'`),
    status: text('status').$type<'open' | 'resolved' | 'dismissed'>().notNull().default('open'),
    resolvedBy: text('resolved_by').references(() => users.id, { onDelete: 'set null' }),
    resolutionNote: text('resolution_note').notNull().default(''),
    resolvedAt: integer('resolved_at'),
    createdAt: integer('created_at').notNull(),
  },
  (t) => [
    index('reports_status_idx').on(t.status, t.createdAt),
    index('reports_target_idx').on(t.targetType, t.targetId),
    check('reports_status_ck', sql`${t.status} in ('open','resolved','dismissed')`),
  ],
);

export const auditEvents = sqliteTable(
  'audit_events',
  {
    id: text('id').primaryKey(),
    scope: text('scope').$type<'platform' | 'community'>().notNull(),
    communityId: text('community_id').references(() => communities.id, { onDelete: 'cascade' }),
    actorId: text('actor_id').references(() => users.id, { onDelete: 'set null' }),
    action: text('action').notNull(),
    targetType: text('target_type'),
    targetId: text('target_id'),
    /** Human-readable label captured at the time (e.g. username), never message content. */
    targetLabel: text('target_label'),
    reason: text('reason'),
    metadata: text('metadata', { mode: 'json' }).$type<Record<string, unknown>>().notNull().default(sql`'{}'`),
    createdAt: integer('created_at').notNull(),
  },
  (t) => [
    index('audit_events_scope_idx').on(t.scope, t.createdAt),
    index('audit_events_community_idx').on(t.communityId, t.createdAt),
    check('audit_events_scope_ck', sql`${t.scope} in ('platform','community')`),
  ],
);

export const appSettings = sqliteTable('app_settings', {
  key: text('key').primaryKey(),
  value: text('value', { mode: 'json' }).$type<unknown>().notNull(),
  updatedAt: integer('updated_at').notNull(),
  updatedBy: text('updated_by'),
});
